### PR TITLE
Fix for "page_expired" error.

### PR DESCRIPTION
**Pull request by mbassan**

### CODE REVIEW

**Comment by dud3** [comment]
Still got the same error ?

**Comment by mbassan** [comment]
Please open frontend/lib/common.php and comment out the line that says `session_regenerate()` with //.

**Comment by dud3** [comment]
I guess this one:
```js
if (empty($ajax)) {
        session_start();
        // session_regenerate();
}
```

Still the same problem ;(.

**Comment by dud3** [comment]
This one happens on `/frontend/htdocs/register.php`

**Comment by mbassan** [comment]
Strange. You can contact me on Skype at support.wlox if you like and we
will try to solve the problem. Might be easier that way.

On Wed, Aug 26, 2015 at 9:18 AM, Dren Kajmakci <notifications@github.com>
wrote:

> This one happens on /frontend/htdocs/register.php
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wlox/wlox-frontend/pull/11#issuecomment-135036802>.
>



-- 
Moisés Bassan
Organic Technologies
moises@organic.com.pa
www.organic.com.pa
Tel: +507 6616-8671
Skype: moises.bassan

**Pull request merged**
